config:
  labfluz:database-url:
    secure: AAABACsFM43/v/RSxa4Qzc9/lpw1Equ1Hk0TnkYC7DOQ1g8kE+wfevt3qjPWFspuVHVq3J4V8sdJ8Z62IfhCkWCKVJc0ZvRcJXgCnpsyIBGc+vNJa5otIKieXJ3CShfxNkE4B9Is9l+3JHx3VBLxrXUiPS1YtqqEyVMKgA+hf1Nhd2TKgEjwH5RmyRLoSxJDw9dDU0zvn0vqX1RMTUvIjEQpoPm1kbj42/jOzzdPcNzh3Cw=
