version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    description: Setup and run application tests
    steps:
      - checkout
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: NevaManagement.Tests
  build:
    build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - checkout
      - run:
          name: Restore 
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/push-docker-image
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - build
          post-steps:
            - heroku/release-docker-image
          filters:
            branches:
              only: main