version: 2.1
  
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    description: Setup and run application tests
    steps:
      - checkout
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: NevaManagement.Tests
  build:
    build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - checkout
      - run:
          name: Restore 
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
  deploy:
    docker:
      - image: alpine:3.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: false
      - run:
          name: Deploy Main to Heroku
          command: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker build . -t NevaManagement-Api
            docker tag NevaManagement-Api registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main