version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: neva_local
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d neva_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  functions:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://dev:dev@postgres:5432/neva_local?sslmode=disable
      - JWT_SECRET=your-local-jwt-secret-key
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: